configure ifra + run migrations buildtry10

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -197,7 +197,36 @@ jobs:
             # exit 1
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}          
-          
+
+  run-migrations:
+    docker:
+      - image: circleci/node:13.8.0 # safe- avoids migration errors best
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update --no-cache tar gzip nodejs npm ansible aws-cli curl
+      - restore_cache:
+          keys: [backend-build]      
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            npm install
+            npm run migrations > migrations_dump.txt
+          # Run and save the migration output above
+          # exit 1
+      - run:
+          name: Send migration results to memstash
+          command: |
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+                curl https://kvdb.io/4vuGUYiUfjAF1ZNYBw5WRL/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+            fi
+          # exit 1
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}               
 
 workflows:
   default:
@@ -219,8 +248,8 @@ workflows:
           #     only: [dev-branch]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-      # - run-migrations:
-      #     requires: [configure-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
       # - deploy-frontend:
       #     requires: [run-migrations]
       # - deploy-backend:
